models.py
from app import db
import uuid
from datetime import datetime
from flask_security import UserMixin, RoleMixin


from utils import simple_slug_generator


class Promotion(db.Model):
    """Promotions model Data Post"""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(70), unique=True, nullable=False)
    slug = db.Column(db.String(75), unique=True)
    description = db.Column(db.String(160), unique=True, nullable=False)
    img = db.Column(db.String(100), nullable=False)
    img_alt = db.Column(db.String(100), nullable=False)
    body = db.Column(db.Text, nullable=False)
    link_casino = db.Column(db.String(300), nullable=False)
    created = db.Column(db.DateTime, default=datetime.now())
    over = db.Column(db.String(3))

    def __init__(self, *args, **kwargs):
        super(Promotion, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = simple_slug_generator(self.title)


    def __repr__(self):
        return '<Promotion id: {}, title: {}>'.format(self.id, self.title)


# Flask Security
roles_user = db.Table('role_users',
                      db.Column('user_id', db.Integer(),
                                db.ForeignKey('user.id')),
                      db.Column('role_id', db.Integer(),
                                db.ForeignKey('role.id'))
                      )


class User(db.Model, UserMixin):
    """Model for Authorization"""
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_user,
                            backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    """Role Model for Site Administration"""
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app.py
from flask import Flask, url_for, redirect, request
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user
from config import Configuration

from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate
from flask_migrate import MigrateCommand

from flask_script import Manager

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView

app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)
from models import Promotion, User, Role


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
    """Закрывает админк от общего доступа"""
    pass


class HomeAdminView(AdminMixin, ModelView):
    """Скрывает админку"""
    pass


class PromotionAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'description', 'img', 'img_alt', 'body', 'link_casino', 'over']


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

admin = Admin(app)
admin.add_view(PromotionAdminView(Promotion, db.session))


# Flask Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db
from promotions.blueprint import promotions


import view

app.register_blueprint(promotions, url_prefix='')


if __name__ == '__main__':
    app.run()

promotions/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Promotion

from flask_security import login_required

promotions = Blueprint('promotions', __name__)


@promotions.route('/')
def main():
    """Home page"""
    data = Promotion.query.all()
    return render_template('main.html', data=data)


@promotions.route('/<slug>')
def promo_detail(slug):
    """Detail page"""
    promotion = Promotion.query.filter(Promotion.slug==slug).first()
    return render_template('promo_detail.html', promotion=promotion)

templates/base.html
<!DOCTYPE html>
<html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>{% block title %}talkgamblers.com{% endblock %}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta http-equiv="x-ua-compatible" content="ie=edge">
            {% block locale %}{% endblock locale %}
            <meta name="description" content="{% block desc %}{% endblock desc %}" />
            <link rel="canonical" href="{% block cann %}{% endblock cann %}" />
            <link rel="preconnect" href="https://analytics.google.com/">
            <link rel="preconnect" href="https://tagmanager.google.com/">
            <link rel="dns-prefetch" href="https://cloudinary.com/">
            <link rel="preload" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&family=Noto+Sans:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap" as="style">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&family=Noto+Sans:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap" />
            {% block meta_og %}
            {% endblock meta_og %}

            {% block css %}
                <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
            {% endblock css %}
        </head>

        <body>
               <header>
                                                <nav>
                                                        <ul class="nav-links">

                                                            <li class=""><a href="" class="logo-text bord-1"><span class="logo-circle" style="font-family: Roboto,sans-serif;font-size: 22px; font-weight: 500;">talkgamblers.com</span></a></li>



                                                        </ul>
                                                </nav>
                                </header>


                                <main>
                                    <div class="grid-container">
                                        {% block content %}
                                        {% endblock content %}
                                    </div>
                                </main>



                {% block script %}
                {% endblock script %}
        </body>
</html>

templates/casino-asside.html
                <div class="article-aside">
                        <div class="bonus-aside-article">
                                    <div class="bonus-title">
                                        <h2 style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight:700;">ALL REVIEWS</h2>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590873924/bonus-tab/betsson_re7zqw.jpg" title="Betsson" alt="logo Betsson"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/betsson-casino" onclick="location.href='https://casinogoodorbad.com/reviews/betsson-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">BETSSON CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="http://record.betsson.com/_cvQpmT4UK60MGjCE5hF4R2Nd7ZgqdRLk/1/" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590872843/bonus-tab/betsafe_cdlgnl.jpg" title="Betsafe" alt="logo Betsafe"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/betsafe-casino" onclick="location.href='https://casinogoodorbad.com/reviews/betsafe-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">BETSAFE CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://bit.ly/3bsZYcO" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590879479/bonus-tab/wish_njt4yf.jpg" title="Wishmaker" alt="logo Wishmaker"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/wishmaker-casino" onclick="location.href='https://casinogoodorbad.com/reviews/wishmaker-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">WISHMAKER CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://media.wishmaker.partners/redirect.aspx?pid=3711&bid=1548" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1595551317/bonus-tab/B184124_ugbzis.jpg" title="bitStarz" alt="logo bitStarz"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/bitstarz-casino" onclick="location.href='https://casinogoodorbad.com/reviews/bitstarz-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">BITSTARZ CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://bs.direct/b287e3cb2" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590882056/bonus-tab/ps_mllgv0.jpg" title="PokerStars" alt="logo PokerStars"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/pokerstars-casino" onclick="location.href='https://casinogoodorbad.com/reviews/pokerstars-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">POKERSTARS CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://secure.starsaffiliateclub.com/C.ashx?btag=a_178615b_2982c_&affid=100975464&siteid=178615&adid=2982&c=" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590882405/bonus-tab/wh_zqjuxk.jpg" title="William Hill" alt="logo William Hill"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/williamhill-casino" onclick="location.href='https://casinogoodorbad.com/reviews/williamhill-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">WILLIAM HILL CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://campaigns.williamhill.com/C.ashx?btag=a_182112b_673c_&affid=1737559&siteid=182112&adid=673&c=" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590884109/bonus-tab/snabbis_fau2jh.jpg" title="Snabbis" alt="logo Snabbis"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/snabbis-casino" onclick="location.href='https://casinogoodorbad.com/reviews/snabbis-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">SNABBIS CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://record.snabbisaffiliates.com/_MlEHUYtTva8DVkvPM80nyWNd7ZgqdRLk/1/" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1595550913/bonus-tab/184En_aaqv40.jpg" title="Energy" alt="logo Energy"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/energy-casino" onclick="location.href='https://casinogoodorbad.com/reviews/energy-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">ENERGY CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://charity.energy.partners/redirect.aspx?pid=28752&bid=5325&redirectURL=http://www.energycasino.com/" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                                    <div class="bonus-tab">
                                            <div class="imgBx">
                                                <div><img src="https://res.cloudinary.com/dtmwfpxu9/image/upload/q_auto,f_auto/v1590949296/bonus-tab/sb_eh4cht.jpg" title="Sportsbet.io" alt="logo Sportsbet"/></div>
                                                <div class="name-casino"><a href="https://casinogoodorbad.com/reviews/sportsbet-casino" onclick="location.href='https://casinogoodorbad.com/reviews/sportsbet-casino'"><p style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 500;color:#707070">SPORTSBET CASINO</p></a></div>
                                                <div class="knopka-hide"><a href="https://partners_click.sportsbet.io/?serial=3440&creative_id=476&anid=" rel="nofollow" class="knopkab" style="font-family:'IBM Plex Sans',sans-serif;font-size:12px;font-weight: 700">PLAY</a></div>
                                            </div>
                                    </div>
                        </div>
                </div>

templates/main.html
{% extends 'base.html' %}



{% block title %}talkgamblers.com{% endblock %}
{% block desc %}The list promotions at of the best online casinos and bookmakers. Here you can express your opinion and study the current offers of the gambling industry.{% endblock desc %}
{% block cann %}{% endblock cann %}

{% block meta_og %}
<meta property="og:type" content="website" />
<meta property="og:site_name" content="talkgamblers.com" />
<meta property="og:url" content="https://talkgamblers.com" />
<meta property="og:title" content="talkgamblers.com" />
<meta property="og:description" content="The list promotions at of the best online casinos and bookmakers. Here you can express your opinion and study the current offers of the gambling industry." />
<meta property="og:image" content="" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@pioner_vova" />
<meta name="twitter:creator" content="@pioner_vova" />
<meta name="twitter:title" content="https://talkgamblers.com" />
<meta name="twitter:description" content="The list promotions at of the best online casinos and bookmakers. Here you can express your opinion and study the current offers of the gambling industry." />
<meta name="twitter:image" content="" />
{% endblock meta_og %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
{% endblock css %}


{% block content %}
    {% for promo in data %}
        <p><a href="{{ url_for('promotions.promo_detail', slug=promo.slug) }}">{{ promo.title }}</a></p>
    {% endfor %}
{% endblock content %}



{% block script %}
    <script src=""></script>
{% endblock script %}

templates/promo_detail.html
{% extends 'base.html' %}


{% block title %}{{ promotion.title }}{% endblock %}
{% block desc %}{{ promotion.description }}{% endblock desc %}
{% block cann %}https://talkgamblers.com/promotions/{{promotion.slug}}{% endblock cann %}

{% block meta_og %}
<meta property="og:type" content="article" />
<meta property="og:site_name" content="talkgamblers.com" />
<meta property="og:url" content="https://talkgamblers.com/promotions/{{promotion.slug}}" />
<meta property="og:title" content="{{ promotion.title }} - Promotions (2020)" />
<meta property="og:description" content="{{promotion.description}}" />
<meta property="og:article:modified_time" content="{{promotion.created}}" />
<meta property="og:image" content="https://talkgamblers.com/static/" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@pioner_vova" />
<meta name="twitter:creator" content="@pioner_vova" />
<meta name="twitter:title" content="{{ promotion.title }} - Promotions (2021)" />
<meta name="twitter:description" content="{{promotion.description}}" />
<meta name="twitter:image" content="https://talkgamblers.com/static/" />
{% endblock meta_og %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/promo-detail.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ajaxcomments.min.css') }}" />
{% endblock css %}



{% block content %}

    <div class="main-content">
                <article>
                    <div class="article-detail">

                        <div class="article-detail-tags">
                        </div>

                        <div class="article-detail-title"><h1 style="font-family:'IBM Plex Sans',sans-serif;font-size:19px;font-weight:500;color:#373b40;">{{ promotion.title }}</h1></div>
                        <div class="article-detail-date" style="font-family:'Noto Sans',sans-serif;font-size:13px;">Update: {{ promotion.created }}

                        </div>
                        <div class="article-detail-body" style="font-family:'Noto Sans',sans-serif;color:#373b40;font-size:14px"><em>{{ promotion.description|safe }}</em><br><br>{{ promotion.body|safe }}</div>
                    </div>


                    <div class="container-article-detail-comment">

                    </div>
                </article>

                <aside>
                    {% include 'casino-asside.html' %}
                </aside>
    </div>

{% endblock content %}

{% block script %}
    <script async src="{{ url_for('static', filename='js/progressive-image.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script  src="{{ url_for('static', filename='js/ajaxcomments.min.js') }}"></script>
{% endblock script %}

templates/promo_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Promotions at Online Casinos (2020){% endblock title %}
{% block desc %}All promotions at the right online casinos and bookmakers. Find the best deposit bonus. Get free spins and be gambling on popular jackpot slots or blackjack.{% endblock desc %}
{% block cann %}https://casinogoodorbad.com/promotions{% endblock cann %}

{% block meta_og %}
<meta property="og:site_name" content="casinogoodorbad.com" />
<meta property="og:title" content="Promotions at Online Casinos (2020)" />
<meta property="og:description" content="All promotions at the right online casinos and bookmakers. Find the best deposit bonus. Get free spins and be gambling on popular jackpot slots or blackjack." />
<meta property="og:url" content="https://casinogoodorbad.com/promotions" />
<meta property="og:image" content="https://casinogoodorbad.com/static/og-promo.jpg" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@pioner_vova" />
<meta name="twitter:creator" content="@pioner_vova" />
<meta name="twitter:title" content="Promotions at Online Casinos (2020)" />
<meta name="twitter:description" content="All promotions at the right online casinos and bookmakers. Find the best deposit bonus. Get free spins and be gambling on popular jackpot slots or blackjack." />
<meta name="twitter:image" content="https://casinogoodorbad.com/static/og-promo.jpg" />
{% endblock meta_og %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/main.min.css' %}" />
{% endblock css %}


{% block content %}
        <div class="main__title__promo__list"><h1 style="font-family:'IBM Plex Sans',sans-serif;font-weight:500;font-size:18px;color:#373b40;">All promotions and first deposit bonuses at the best online casinos (2020)</h1>
        <p style="font-family:'Noto Sans',sans-serif;font-size:13px">Current conditions for carrying out promotions, a list of restrictions, all the necessary information, rakeback programs for poker players. Counting cards in blackjack or playing slots hoping to win the jackpot? At casinogoodorbad.com you will always find casinos with the best promo.</p></div>
        <div class="promo__list">

            {% for promo in object_list %}
                <div class="card__news">
                    <div class="linkblock" onclick="location.href='{% url 'promo_detail_en' slug=promo.slug %}'">
                        <div class="news__main__child">
                            <div class="news__main__page__title"><a href="{% url 'promo_detail_en' slug=promo.slug %}" class="promo__list__title__h2"><h2 style="font-family: 'IBM Plex Sans', sans-serif; font-weight: 500;font-size: 14px;">{{ promo.title }}</h2></a></div>
                        </div>
                        <div class="news__description__main__page" style="font-family: 'Noto Sans', sans-serif; font-size: 13px;">{{ promo.description }}</div>
                        <div class="foot__date__promo__list" style="font-family:'Noto Sans',sans-serif;font-size:12px;">
                            {% if promo.over == "yes" %}
                                    <span class="over__promo__list" style="font-family: Roboto, sans-serif;">is over</span>
                            {% else %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock content %}


{% block script %}
<script async src="{% static 'js/progressive-image.js' %}"></script>
{% endblock script %}

templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    {{ field.label }} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>{{ _('Menu') }}</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

templates/security/change_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Change password') }}</h1>
<form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
  {{ change_password_form.hidden_tag() }}
  {{ render_field_with_errors(change_password_form.password) }}
  {{ render_field_with_errors(change_password_form.new_password) }}
  {{ render_field_with_errors(change_password_form.new_password_confirm) }}
  {{ render_field(change_password_form.submit) }}
</form>

templates/security/forgot_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Send password reset instructions') }}</h1>
<form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ render_field_with_errors(forgot_password_form.email) }} 
  {{ render_field(forgot_password_form.submit) }}
</form>
{% include "security/_menu.html" %}

templates/security/login_user.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
</form>
{% include "security/_menu.html" %}

templates/security/register_user.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Register') }}</h1>
<form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
  {{ register_user_form.hidden_tag() }}
  {{ render_field_with_errors(register_user_form.email) }}
  {{ render_field_with_errors(register_user_form.password) }}
  {% if register_user_form.password_confirm %}
    {{ render_field_with_errors(register_user_form.password_confirm) }}
  {% endif %}
  {{ render_field(register_user_form.submit) }}
</form>
{% include "security/_menu.html" %}

templates/security/reset_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Reset password') }}</h1>
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
  {{ reset_password_form.hidden_tag() }}
  {{ render_field_with_errors(reset_password_form.password) }}
  {{ render_field_with_errors(reset_password_form.password_confirm) }}
  {{ render_field(reset_password_form.submit) }}
</form>
{% include "security/_menu.html" %}

templates/security/send_confirmation.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Resend confirmation instructions') }}</h1>
<form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
  {{ send_confirmation_form.hidden_tag() }}
  {{ render_field_with_errors(send_confirmation_form.email) }}
  {{ render_field(send_confirmation_form.submit) }}
</form>
{% include "security/_menu.html" %}

templates/security/send_login.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="send_login_form">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit) }}
</form>
{% include "security/_menu.html" %}